package com.uma.mestrado.persuasive_profiles.database.entities;
// Generated Jan 17, 2021 10:36:05 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Gender generated by hbm2java
 */
@Entity
@Table(name="gender"
    ,catalog="persuasive_computation"
    , uniqueConstraints = @UniqueConstraint(columnNames="type") 
)
public class Gender  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Set<Person> persons = new HashSet<Person>(0);

    public Gender() {
    }

	
    public Gender(String type) {
        this.type = type;
    }
    public Gender(String type, Set<Person> persons) {
       this.type = type;
       this.persons = persons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type", unique=true, nullable=false, length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gender")
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }




}


