package com.uma.mestrado.persuasive_profiles.database.entities;
// Generated Jan 17, 2021 7:37:12 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * InfluencePrinciple generated by hbm2java
 */
@Entity
@Table(name="influence_principle"
    ,catalog="persuasive_computation"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class InfluencePrinciple  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set<Historic> historics = new HashSet<Historic>(0);

    public InfluencePrinciple() {
    }

	
    public InfluencePrinciple(String name) {
        this.name = name;
    }
    public InfluencePrinciple(String name, String description, Set<Historic> historics) {
       this.name = name;
       this.description = description;
       this.historics = historics;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="influencePrinciple")
    public Set<Historic> getHistorics() {
        return this.historics;
    }
    
    public void setHistorics(Set<Historic> historics) {
        this.historics = historics;
    }




}


